name: Bug Report
description: Report a software or web bug
labels: ["it: bug", "-Needs: Triage"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Impacts productivity
        - High - Blocking work
        - Critical - System down
    validations:
      required: true

  - type: input
    id: application
    attributes:
      label: Application
      description: What application is affected? (pre-filled with this repo, edit if different)
      placeholder: "e.g., Web portal, Mobile app, API"
      value: "enhanced-people"
    validations:
      required: true

  - type: input
    id: browser-os
    attributes:
      label: Browser/OS
      description: What browser and operating system are you using?
      placeholder: "e.g., Chrome 120 on Windows 11"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in detail
      placeholder: "Describe what you expected vs what actually happened"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or screenshots
      description: Please copy and paste any relevant log output or describe screenshots
      render: shell
    validations:
      required: false

  - type: dropdown
    id: urgent
    attributes:
      label: Urgent?
      description: Does this need immediate attention?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
