name: Hardware Issue
description: Report a problem with physical hardware or devices
labels: ["Type: Hardware", "-Needs: Triage"]
body:
  - type: input
    id: contact-phone
    attributes:
      label: Contact Phone
      description: Optional phone number for follow-up
      placeholder: "555-555-5555"
    validations:
      required: false

  - type: dropdown
    id: contact-method
    attributes:
      label: Preferred Contact Method
      options:
        - E-mail
        - Phone
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low - Minor inconvenience
        - Medium - Impacts productivity
        - High - Blocking work
        - Critical - System down
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device/Equipment
      description: What hardware is affected?
      placeholder: "e.g., Workstation, Printer, Network switch, Server"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the device located?
      placeholder: "e.g., Office 201, Server room, Remote - home office"
    validations:
      required: false

  - type: input
    id: make-model
    attributes:
      label: Make/Model
      description: Device manufacturer and model if known
      placeholder: "e.g., Dell OptiPlex 7090, HP LaserJet Pro"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the hardware issue in detail
      placeholder: "Describe symptoms, error lights, sounds, etc."
    validations:
      required: true

  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting Already Tried
      description: What have you already tried?
      placeholder: |
        - Restarted device
        - Checked cables
        - etc.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or photos
      description: Please describe any error messages or attach photos
      render: shell
    validations:
      required: false

  - type: dropdown
    id: urgent
    attributes:
      label: Urgent?
      description: Does this need immediate attention?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
